### ISSUE TITLE
Implement task endpoints

### ISSUE THREAD

**Issue by Crevil** [lokalise/go-lokalise-api#11]
Documentation: https://lokalise.co/api2docs/go/#resource-tasks

**Endpoints**

- [x] List all tasks (paginated)
- [x] Create a task
- [x] Retrieve a task
- [x] Update a task
- [x] Delete a task

**Comment by Crevil** [comment]
Documentation states that task descriptions is a `number` but the payload examples (and the name of the field) indicates a `string`. Is this a bug in the documentation, @andrewi-wd ?

https://lokalise.co/api2docs/go/#object-tasks

**Comment by Crevil** [comment]
Further more. The `languages` field is documented as an object but the example payloads indicate an array of objects.

**Comment by Crevil** [comment]
And further more: 
- `keys_count` in `languages` is documented as a string but examples show a number
- `words_count` in `languages` is documented as a string but examples show a number
- `users` in `languages` is documented as an object but examples show an array of objects

**Comment by Crevil** [comment]
@nickustinov Can you clarify the above?

**Comment by Crevil** [comment]
The Create task response examples shows an array value `[]` on the `initial_tm_leverage` field of langauges, but the [Task documents](https://lokalise.co/api2docs/curl/#object-tasks) this as an array.

The second language object in the `languages` field has two `keys` fields. One with the array of key IDs and the second one with the value `3`. The last one could look like the `keys_count` field?

**Comment by nickustinov** [comment]
@andrewi-wd Could you please clarify?

**Comment by andrewi-wd** [comment]
@Crevil Thanks for pointing this out.

`description` - string
`key_count` - number
`words_count` - number
Will fix docs asap.

both `languages` and `users` - array of objects.
```
[
    {
        "key": "value"
    },
    {
        "key": "value"
    },
]
```
Unfortunately our doc tool isn't able to display it correctly. There are few more properties like them in our docs (property type is an object, but description states that it is a "List"). We'll think how to make them more clear.

`initial_tm_leverage` - Looks like a bug, it certainly should not be an array or an object. This property can be enabled/disabled for each task, that is why its dynamic. How do you think which option would be better:
* `object` | `null`
* `object` | empty `object`
* `object` | skipped parameter
?

`keys` - Could you please clarify? We have `keys` and `keys_count` only on our end.
