### ISSUE TITLE
Testing setup

### ISSUE THREAD

**Issue by Crevil** [lokalise/go-lokalise-api#14]
Is there any CI tooling available in your development setup that we can use e.g. CircleCI, Travis?

It would be great to have it running builds and unit tests (maybe even integration tests) on changes (and PRs)

**Comment by nickustinov** [comment]
We are using Jenkins, however I'd rather set up a separate box for this, which one do you prefer?

**Comment by Crevil** [comment]
I've used Travis before for OSS projects so that would be my go to.

**Comment by nickustinov** [comment]
Great. We have just released offical php libraries, just fyi https://github.com/lokalise/php-lokalise-api
