### ISSUE TITLE
Implement projects endpoints

### ISSUE THREAD

**Issue by Crevil** [lokalise/go-lokalise-api#2]
Documentation: https://lokalise.co/api2docs/curl/#resource-projects

**Endpoints**

- [x] List all projects (paginated)
- [x] Create a project
- [x] Retrieve a project
- [x] Update a project
- [x] Empty project
- [x] Delete a project

**Comment by Crevil** [comment]
@andrewi-wd Can you verify if I found another documentation bug?

The documentation specs that `created_at` is a string like `2018-12-31 12:00:00`, but when requesting the API I get `2018-02-09 07:56:41 (Etc/UTC)`.

Right now I'm not mapping to a Go `time.Time` struct, so it doesn't matter for the functionality, but I'd like to do that later on.

**Comment by Crevil** [comment]
Further more the `created_by` field is documented as a string but the API returns an integer (which is what I expected)

**Comment by andrewi-wd** [comment]
@Crevil 
`created_at` - string with trailing timezone: 2018-02-09 07:56:41 (Etc/UTC)
`created_by` - integer, greater than zero
`created_by_email` - string

I'll fix documentation

**Comment by Crevil** [comment]
Great. Thanks
